### ISSUE TITLE
Try DSK for efficient large k-mer extraction

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/amr#1]
- Compile DSK
- Run on one or more genomes

**Comment by joewandy** [comment]
http://minia.genouest.org/dsk/

**Comment by 2064240P** [comment]
https://github.com/GATB/dsk/releases
They also seem to have executables. Tried the mac one and it seems to work fine. Didn't quite manage to compile it from scratch from some reason but will investigate why

**Comment by joewandy** [comment]
Run DSK on the data downloaded from issue #5 . The output is hdf5 file, which we can load back into python.

**Comment by youngfran** [comment]
Added a notebook to run dsk and then reload it into python . I  run it on the dataset for k = 2 , I have a 160MB .gz file which  contains an .h5 file for each genome. I could will put it on Joe's dropbox .

**Comment by joewandy** [comment]
What does k=1 mean? Could you share the file to me via the uni's file transfer https://transfer.gla.ac.uk/, thanks!

**Comment by youngfran** [comment]
Oops typo, kmer-size was set to 21 
I will transfer files later when I am at the CVR.

**Comment by youngfran** [comment]
Did you get the files OK. I wasn’t sure I had transferred them properly.
Fran

Sent from my iPad

On 3 Jul 2019, at 23:06, Joe Wandy <notifications@github.com<mailto:notifications@github.com>> wrote:


What does k=1 mean? Could you share the file to me via the uni's file transfer https://transfer.gla.ac.uk/, thanks!

**Comment by joewandy** [comment]
The file is only 45 bytes? Something seems wrong
![Screenshot from 2019-07-10 11-19-33](https://user-images.githubusercontent.com/2523391/60961748-c150b780-a304-11e9-8e35-55df23e6b82f.png)

**Comment by youngfran** [comment]
Sorry I don't know what I did there, I was in too much of a rush.
Hopefully they are there now.
https://transfer.gla.ac.uk/pickup?claimID=SvjEJDVnheJ6dVjd&claimPasscode=zFQnaAbgHqn6eMj9

**Comment by joewandy** [comment]
Got it now :smile: Are these the results from running DSK on the fasta files of N. gonorrhoeae (what we discussed in issue #5 )? Or is it from some test data?

**Comment by youngfran** [comment]
Hi , yes it is the N.gon. dataset as discussed. the metadata file should be in with it with the antibiotic resistance label.
It is the(nucleic acid) fasta files downloaded via Partic tools. Alex was trying to get at the fasta files with the amino acid sequences as well - which are the ones we want.
 Then  I ran dsk with kmer-size set to 0. It crashed a couple of times when it was working through all the files and I just re-ran it on the remaining files so a couple of them may not be complete.

**Comment by 2064240P** [comment]
Do we also want to run dsk on the amino acid seqs as well? I was just going to run cd-hit.

**Comment by 2064240P** [comment]
Done. Dsk settings same as the settings in the patric paper.
