### ISSUE TITLE
Download the data and share them

### ISSUE THREAD

**Issue by joewandy** [sdrogers/amr#5]
N. gonorrhoeae | Azithromycin
392 genomes, 214 are resistant, 178 susceptible.

Data can be downloaded from:
https://github.com/aldro61/kover2_paper/tree/master/data
https://github.com/aldro61/kover2_paper/blob/master/data/download_genomes.py

**Comment by 2064240P** [comment]
We have the downloaded tuberculosis dataset. Patric tools works for downloading data.
